"""autogenerate

Revision ID: 7e7056f94467
Revises: 
Create Date: 2025-12-24 23:22:23.986032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e7056f94467'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('category_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['article_categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_article_categories_active', 'article_categories', ['is_active'], unique=False)
    op.create_index('idx_article_categories_slug', 'article_categories', ['slug'], unique=False)
    op.create_table('attributes',
    sa.Column('attribute_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('attribute_type', sa.Enum('text', 'number', 'boolean', 'select', name='attribute_types'), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    op.create_table('brands',
    sa.Column('brand_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('english_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('categories',
    sa.Column('category_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('contact_messages',
    sa.Column('message_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('is_responded', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('vendors',
    sa.Column('vendor_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_table('articles',
    sa.Column('article_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('meta_title', sa.String(length=300), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_image', sa.String(length=500), nullable=True),
    sa.Column('author_name', sa.String(length=150), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.category_id'], ),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_articles_active', 'articles', ['is_active'], unique=False)
    op.create_index('idx_articles_category', 'articles', ['category_id'], unique=False)
    op.create_index('idx_articles_featured', 'articles', ['is_featured'], unique=False)
    op.create_index('idx_articles_published', 'articles', ['is_published'], unique=False)
    op.create_index('idx_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('idx_articles_slug', 'articles', ['slug'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('order_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('idx_orders_customer', 'orders', ['customer_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('vendor_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('brand_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_products_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_products_brand', 'products', ['brand_id'], unique=False)
    op.create_index('idx_products_category', 'products', ['category_id'], unique=False)
    op.create_table('article_comments',
    sa.Column('comment_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('article_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('author_name', sa.String(length=150), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_ip', sa.String(length=45), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['article_comments.comment_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index('idx_comments_approved', 'article_comments', ['is_approved'], unique=False)
    op.create_index('idx_comments_article', 'article_comments', ['article_id'], unique=False)
    op.create_index('idx_comments_parent', 'article_comments', ['parent_id'], unique=False)
    op.create_table('article_images',
    sa.Column('image_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('article_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index('idx_article_images_article', 'article_images', ['article_id'], unique=False)
    op.create_index('idx_article_images_order', 'article_images', ['sort_order'], unique=False)
    op.create_table('product_attributes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('attribute_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.attribute_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attribute_id', name='unique_product_attribute')
    )
    op.create_index('idx_product_attrs_attribute', 'product_attributes', ['attribute_id'], unique=False)
    op.create_index('idx_product_attrs_product', 'product_attributes', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('image_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index('idx_product_images_order', 'product_images', ['sort_order'], unique=False)
    op.create_index('idx_product_images_product', 'product_images', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('variant_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('size_value', sa.String(length=50), nullable=True),
    sa.Column('size_unit', sa.String(length=20), nullable=True),
    sa.Column('wholesale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_variants_active', 'product_variants', ['is_active'], unique=False)
    op.create_index('idx_variants_product', 'product_variants', ['product_id'], unique=False)
    op.create_index('idx_variants_sku', 'product_variants', ['sku'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('variant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index('idx_order_items_order', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_variants_sku', table_name='product_variants')
    op.drop_index('idx_variants_product', table_name='product_variants')
    op.drop_index('idx_variants_active', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('idx_product_images_product', table_name='product_images')
    op.drop_index('idx_product_images_order', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('idx_product_attrs_product', table_name='product_attributes')
    op.drop_index('idx_product_attrs_attribute', table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index('idx_article_images_order', table_name='article_images')
    op.drop_index('idx_article_images_article', table_name='article_images')
    op.drop_table('article_images')
    op.drop_index('idx_comments_parent', table_name='article_comments')
    op.drop_index('idx_comments_article', table_name='article_comments')
    op.drop_index('idx_comments_approved', table_name='article_comments')
    op.drop_table('article_comments')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_brand', table_name='products')
    op.drop_index('idx_products_active', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_orders_customer', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_articles_slug', table_name='articles')
    op.drop_index('idx_articles_published_at', table_name='articles')
    op.drop_index('idx_articles_published', table_name='articles')
    op.drop_index('idx_articles_featured', table_name='articles')
    op.drop_index('idx_articles_category', table_name='articles')
    op.drop_index('idx_articles_active', table_name='articles')
    op.drop_table('articles')
    op.drop_table('vendors')
    op.drop_table('site_settings')
    op.drop_table('customers')
    op.drop_table('contact_messages')
    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_table('attributes')
    op.drop_index('idx_article_categories_slug', table_name='article_categories')
    op.drop_index('idx_article_categories_active', table_name='article_categories')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
