"""Migration script template
Generated by Alembic.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a7bc015f761c'
down_revision = ('4b637a7f399f', 'f8f15b67f141')
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
