"""add english_name and logo_url to brands
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'daa1150148dc'
down_revision = '312518f055cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('english_name', sa.String(length=255), nullable=True))
    op.add_column('brands', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'logo_url')
    op.drop_column('brands', 'english_name')
    # ### end Alembic commands ###
