"""Migration script template
Generated by Alembic.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'feb04b3d5c00'
down_revision = '67e1b733f7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('blog_category_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('blog_category_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('blog_posts',
    sa.Column('post_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.String(length=1000), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='post_status'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.blog_category_id'], ),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_posts_published', 'blog_posts', ['published_at'], unique=False)
    op.create_index('idx_posts_status', 'blog_posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_status', table_name='blog_posts')
    op.drop_index('idx_posts_published', table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
